# Generated by Django 4.0.6 on 2022-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=12)),
                ('date', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
