# Generated by Django 4.0.6 on 2022-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquery',
            name='project',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
