# Generated by Django 4.0.6 on 2022-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
