# Generated by Django 4.0.6 on 2022-10-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enquery',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
