# Generated by Django 4.1 on 2023-01-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_apply_status_enquery_status_register_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_des', models.TextField()),
                ('course_img', models.FileField(upload_to='course')),
                ('course_cre_date', models.DateField(auto_now_add=True, null=True)),
                ('course_vacancy', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
