# Generated by Django 4.1 on 2023-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
