# Generated by Django 4.1 on 2023-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_apply_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquery',
            name='enq_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
