# Generated by Django 4.1 on 2023-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_enquery_enq_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_head', models.CharField(max_length=255)),
                ('ev_des', models.TextField()),
                ('ev_img', models.FileField(upload_to='events')),
                ('event_cre_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
