# Generated by Django 4.1 on 2023-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField()),
                ('news_cre_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
