# Generated by Django 4.1 on 2023-01-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_newsupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(auto_now_add=True, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('subj', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('send_status', models.IntegerField(default=0)),
            ],
        ),
    ]
