# Generated by Django 4.1 on 2023-01-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='UserMessages',
        ),
    ]
