# Generated by Django 4.1 on 2023-01-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_messages_usermessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testi_name', models.CharField(max_length=255)),
                ('testi_des', models.TextField()),
                ('testi_img', models.FileField(upload_to='testimonial')),
                ('testi_cre_date', models.DateField(auto_now_add=True, null=True)),
                ('testi_desecri', models.IntegerField(default=0)),
            ],
        ),
    ]
