# Generated by Django 4.1 on 2023-01-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testi_des',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testi_desecri',
            field=models.TextField(),
        ),
    ]
