# Generated by Django 3.2.16 on 2023-01-25 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_testimonial_testi_des_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(default='', max_length=255)),
                ('post_name', models.CharField(default='', max_length=255)),
                ('post_disc', models.TextField(default='')),
                ('qualific', models.CharField(default='', max_length=255)),
                ('type_job', models.CharField(default='', max_length=150)),
                ('last_date', models.DateField(null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('job_status', models.CharField(default=0, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appli_loc', models.CharField(default='', max_length=255)),
                ('appli_name', models.CharField(default='', max_length=255)),
                ('appli_email', models.TextField(default='')),
                ('appli_phone', models.CharField(default='', max_length=255)),
                ('appli_date', models.DateField(auto_now_add=True, null=True)),
                ('appli_resume', models.FileField(default='', upload_to='resume')),
                ('appli_status', models.CharField(default=0, max_length=150)),
                ('appli_job', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vacancys')),
            ],
        ),
    ]
