# Generated by Django 4.2.7 on 2024-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_thememodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememodel',
            name='theme_name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
